### ISSUE TITLE
修改MIPS32 _heap实现

### ISSUE THREAD

**Issue by jiangyy** [NJUCS-ComputerSystemLab-2017/Abstract-Machine#12]
ld会增加一些符号，比如`_end`表示.bss的结束，相应还有`__bss_start`, `_data`等，可以用来确定堆区的位置。

如果内核被加载到连续的内存位置，可以定义`extern char _end;`，然后用`&_end`作为堆区的开始，物理内存的最大值作为堆区的结尾。

物理内存的最大值不合适定义在头文件里，可以在loader.ld里作为一个符号给出。

**Comment by jiangyy** [comment]
bss和栈可以做类似处理，AM部分的代码不需要知道具体的地址。

**Comment by reccetear** [comment]
change heap from 0xf2000000 to 0xf40000000
change bss from 0xf0000004 to 0x1ffffffc
change stack from 0xf7fffffc to 0x40000004

**Comment by sashimi-yzh** [comment]
不是說用`extern char _end`的方法得到堆區的開始嗎? 6782a8d393 中的代碼怎麼還是寫死的? 這樣以後來了一個大點的程序你的代碼就會出問題.

**Comment by jiangyy** [comment]
学用一下ld script。可以在里面加符号的，数值不要同时硬编码在两个地方。

http://xenyinzen.wikidot.com/os-dev:explain-a-ldscript

**Comment by userhr** [comment]
change heap from 0xf2000000 to 0xf40000000
change bss from 0xf0000004 to 0x1ffffffc
change stack from 0xf7fffffc to 0x40000004

这段话是什么意思？是说bss从0x1ffffffc往上长，栈从0x40000004往下长吗？0x40000004和0x1ffffffc都是非法地址，现在bram是从0往上256k，ddr是从0xf0000000往上128M

**Comment by jiangyy** [comment]
这段代码可以@userhr，你先把link script搞定，确保程序里能得到ddr开始的位置、ddr结束的位置、bss结束的位置，然后把bss加载到ddr开始位置就行了。

**Comment by reccetear** [comment]
bbs 加载到ddr开始处
bss 的end为heap的开始处
