### ISSUE TITLE
代码清理

### ISSUE THREAD

**Issue by jiangyy** [NJUCS-ComputerSystemLab-2017/Abstract-Machine#13]
1. am.c和video.c内含代码太少，把内容合并到trm.c和ioe.c里。
2. video.c typo。
3. 保持同一个文件的代码风格一致，不要使用tab锁进。

其他coding style参考https://users.ece.cmu.edu/%7Eeno/coding/CCodingStandard.html

**Comment by reccetear** [comment]
已经成功清理了代码，修复了代码格式，并已经merge到了master上
